import { ApiProperty } from "@nestjs/swagger";

export class ProblemDetailsDTO {
  @ApiProperty({
    type: "string",
    format: "uri",
    description: "A URI reference that identifies the problem type. We do use non-resolvable URIs.",
    example: "error:api@clientmodbadges:internal-server-error",
    maxLength: 1024
  })
  type?: string;

  @ApiProperty({
    type: "integer",
    format: "int32",
    description: "The HTTP status code generated by the origin server for this occurrence of the problem.",
    example: 500,
    minimum: 100,
    maximum: 599
  })
  status?: number;

  @ApiProperty({
    type: "string",
    description:
      "A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization.",
    example: "Internal Server Error",
    maxLength: 1024
  })
  title?: string;

  @ApiProperty({
    type: "string",
    description: "A human-readable explanation specific to this occurrence of the problem.",
    example: "An internal error happened during request processing. Please try again later.",
    maxLength: 4096
  })
  detail?: string;
}
